# App Dockerfile
# Project: YumiBung
# Maintaner: David H Tekwie <yamis.spiriteagle@gmail.com>
# Date: April 2023
version: "3.9"

# Networks
networks:
  yumibung-network:
    driver: bridge

# Volumes
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:

# Services
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    container_name: yumibung_app
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./app
        target: /work/app
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - yumibung-network

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    container_name: yumibung_web
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./app
        target: /work/app
    networks:
      - yumibung-network

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: yumibung_db
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - yumibung-network